/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arroz;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * Jackson seu lindão
 */
public class Janela extends javax.swing.JFrame {
    ArrayList<String> lista = new ArrayList<>();

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        resposta = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        btnRmv = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(campoItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 228, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Pessoa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btnAdd.setText("Morte");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 228, 35));

        resposta.setForeground(new java.awt.Color(240, 240, 240));
        resposta.setText("Lista de Pessoas");
        jPanel1.add(resposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 272, -1));

        btnedit.setText("Salvar");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 228, 35));

        btnRmv.setText("Mudar algo");
        btnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvActionPerformed(evt);
            }
        });
        jPanel1.add(btnRmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 228, 35));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arroz/d1hw6x6-a531a74f-4c45-4bd2-8e7a-309cfbe512a0.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String elemento = campoItem.getText();//Obter Texto
        int tempo = 60;
        if (verificaSeExiste(elemento) == true) {
            JOptionPane.showMessageDialog(this, "Este item já existe!");
        } else {
            while(tempo != 0){
            
            lista.add(elemento +" 00:" + tempo);// adicionar na lista
            campoItem.setText(null);//Limpar o campo de texto
            exibeLista();
            tempo--;
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        String elemento = campoItem.getText();//Obter Texto
        lista.remove(elemento);// Remover da lista
        campoItem.setText(null);//Limpar o campo de texto
        exibeLista();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvActionPerformed
        String elemento = campoItem.getText();//Obter Texto
        if (verificaSeExiste(elemento) == true) {
            String correct = JOptionPane.showInputDialog(this, "Corrija!");
            int rmv = lista.indexOf(elemento);
            lista.set(rmv, correct);
            campoItem.setText(null);//Limpar o campo de texto
            exibeLista();
        } else {
            JOptionPane.showMessageDialog(this, "Essa pessoa ainda não está na lista, inclua!");
        }
    }//GEN-LAST:event_btnRmvActionPerformed
    public void exibeLista() {
        String html = "<html>Lista de Pessoas<br><br>";
        for (String item : lista) {
            html += item + "<br>";
        }
        html += "</html>";
        resposta.setText(html);
    }

    public boolean verificaSeExiste(String palavra) {
        for (String item : lista) {//Para cada item contido na lista
            if (item.equals(palavra)) {//se o item for igual à palavra
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRmv;
    private javax.swing.JButton btnedit;
    private javax.swing.JTextField campoItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resposta;
    // End of variables declaration//GEN-END:variables
}
